[browser]
serverAddress = "158.160.45.79"

[server]
address = "0.0.0.0" # Опционально, но рекомендуется для серверов
# enableCORS = false
# enableXsrfProtection = false # ВАЖНО: Это снижает безопасность, используйте только для теста!
# maxUploadSize = 200 # Оставьте или закомментируйте, для 15КБ неважно

[logger]
level = "debug" # Может дать больше информации в логах сервера